name: test_dispatcher_filters
on: [push]
jobs:
  test_dispatcher_filters:
    container:
      image: alpine:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apk add apache2
      - run: ls -la
      - run: ls -la /etc/apache2/conf.d
